version: '3'
services:
    web-py:
        build:
          context: .
        volumes:
          - ./app:/src/app
        env_file:
          - ./.env
        environment:
          - VIRTUAL_HOST=${VIRTUAL_HOST}
          - VIRTUAL_PORT=${APP_PORT}
          - LETSENCRYPT_HOST=${VIRTUAL_HOST}
          - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    db-py:
        image: postgres:14-alpine
        ports:
          - "${DB_PORT}:${DB_PORT}"
        volumes:
          - postgres_data:/var/lib/postgresql/data/
        environment:
          POSTGRES_USER: ${DB_USER}
          POSTGRES_PASSWORD: ${DB_PASS}
          POSTGRES_DB: ${DB_NAME}
volumes:
    postgres_data:      
networks:
  default:
    name: nginx-proxy
    external: true
